sudo: false
language: node_js
addons:
  sonarcloud:
    organization: "ravi-kishan123"
    token:
      secure: "94c846541dbc084efcc4c371082888db2f18db08"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "12.18.1"
before_install:
  - npm install -g npm@latest
install:
  - npm install
before_script: 
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - sonar-scanner
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
