sudo: false
language: node_js
addons:
  sonarcloud:
    organization: "ravi-kishan123"
    token: 
      secure: "SQXOrQhA73ofc+e5HL8WCNMjveNcLwQNJRPCHvGmwYTIulPophjpo1mTM+mu38e06Hw9Ebwmjs2Dfh0ikQu16GqEn+k3cC/HSThIs2EqE7uUAfDfwp4lMfAx08vveVgo7j3dSM8mPPPNofyZbqYJPz2Im5TvG0yiC8KXlTx/509jhwyyaBgJgEwrGXSaZORrJSH87MCYnE57FfKjLcx0u7JRB6/vu6RKjzM8F0P5mWduAOdWqe6KC8Tjc6FWCc063CmOaydFdLx7jSMetcQthFfTUXDcnRYkJXkbsUuR0H0OTToHoU82ZQpuIW1T92XKhYOC/jIWMAnFkv1Sv2WrSwA3oW4SSgnEkJQXM653DvanocPUbmhNjCSi5/4AOSMpIk9HlIa2y/2qqom0CTsQpqWF7CkF0ura+FpEyfCnnDJUyZ83dBbo4FA5RbfIUtU81jLR5Dw0gYgOXXcSpTokqmKw59ReL4OoFYr3DTklg5C9DtjtfmNw0fqQh167uHVzzsUGcZ+r/2T86qZ0ljveO7D6mZHXSAe1T1uDW3DbLnjmeh2Z2EjmyKURGRAe6DViu0zurkpSiO1yy8BJn5cIN+1dvsj/a1tHT7VV80+IuFMQZTa/t2TufhMX7k3fWIeoJj+y4KIokzR2OAEliqF1UuOs7qGpIJCB/uQmw6aNTOY="
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "12.18.1"
before_install:
  - npm install -g npm@latest
install:
  - npm install
before_script: 
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - sonar-scanner
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
