sudo: false
language: node_js
addons:
  sonarcloud:
    organization: "ravi-kishan"
    token: 
      secure: 4260434368463156aa6d9669e45f441e111e8c75
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "12.18.1"
before_install:
  - npm install -g npm@latest
install:
  - npm install
before_script: 
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - sonar-scanner
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
