sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12.18.1"
before_install:
  - npm install -g npm@latest
before_script: 
  - npm prune
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run semantic-release
